services:
  - type: web
    name: url-shortener-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: BASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: REDIS_URL
        sync: false
